pipeline {
    agent any

    environment {
        IMAGE_NAME = "order-ms"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build with Maven') {
            steps {
                dir('order-ms') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKERHUB_USER',
                    passwordVariable: 'DOCKERHUB_PASS'
                )]) {
                    dir('order-ms') {
                        sh '''
                            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
                            docker build -t $DOCKERHUB_USER/${IMAGE_NAME}:$BUILD_NUMBER .
                            docker push $DOCKERHUB_USER/${IMAGE_NAME}:$BUILD_NUMBER
                            docker rmi $DOCKERHUB_USER/${IMAGE_NAME}:$BUILD_NUMBER || true
                        '''
                    }
                }
            }
        }
    }
}

